# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b7584aa96e96e5cbd0d626d68aba6dd4b9fae6680943a53aea50e9edb16f2db70a3fe1c3b3afe41f1be2a56863e5fe4360c0638b7008c322df90a8a9ba581df

test:
  secret_key_base: be05955c0883fb6533e553bb6028cfcf700d835e8aaf0790e7ab818475b1ef7101842ef7d6689aa1d4595fc8a706277d07841649bdf7971325f75b0f6f70cde0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
